### ISSUE TITLE
Prerequisites for installation: newbie problems with import? (related to add_attachment.py)

### ISSUE THREAD

**Issue by knmnyn** [acl-org/acl-anthology#441]
Hi all:

Downloaded the repo with hopes that I could make a `add_doi.py` script for the DOI assignation, but running into initialization problems.  Hope that someone can help on this -- tried to look through issues, stack(overflow/exchange) but not sure how to resolve.

I'm trying to copy and modify @mjpost 's `add_attachment.py` to add a script that can insert the correct DOI tags after assignation.  However I'm failing on simple imports.  The line:

`from anthology.utils import build_anthology_id, deconstruct_anthology_id`

fails in two instances (the second, after I commented out the lines causing difficulty):

1. Traceback (most recent call last):
  File "bin/add_attachment.py", line 47, in <module>
    from anthology.utils import deconstruct_anthology_id
  File "/Users/knmnyn/Downloads/acl-anthology-master/bin/anthology/__init__.py", line 1, in <module>
    from .anthology import Anthology
  File "/Users/knmnyn/Downloads/acl-anthology-master/bin/anthology/anthology.py", line 22, in <module>
    from .formatter import MarkupFormatter
  File "/Users/knmnyn/Downloads/acl-anthology-master/bin/anthology/formatter.py", line 25, in <module>
    from .utils import stringify_children, remove_extra_whitespace
  File "/Users/knmnyn/Downloads/acl-anthology-master/bin/anthology/utils.py", line 24, in <module>
    from .people import PersonName
  File "/Users/knmnyn/Downloads/acl-anthology-master/bin/anthology/people.py", line 18, in <module>
    import anthology.formatter as my_formatter
**AttributeError: module 'anthology' has no attribute 'formatter'**

2. Traceback (most recent call last):
  File "bin/add_attachment.py", line 38, in <module>
    from anthology.utils import build_anthology_id, deconstruct_anthology_id
  File "/Users/knmnyn/Downloads/acl-anthology-master/bin/anthology/__init__.py", line 1, in <module>
    from .anthology import Anthology
  File "/Users/knmnyn/Downloads/acl-anthology-master/bin/anthology/anthology.py", line 26, in <module>
    from .volumes import Volume
  File "/Users/knmnyn/Downloads/acl-anthology-master/bin/anthology/volumes.py", line 23, in <module>
    from .sigs import SIGIndex
  File "/Users/knmnyn/Downloads/acl-anthology-master/bin/anthology/sigs.py", line 33, in <module>
    defaults=[None, None, None, None],
**TypeError: namedtuple() got an unexpected keyword argument 'defaults'**

Any leads for what I'm doing wrong?

**Comment by mbollmann** [comment]
This looks like you're using a Python version < 3.7.

**Comment by mjpost** [comment]
Yes, I think that's your problem.

We should add a check into scripts for this that reports an error, to avoid this kind of confusion.

**Comment by knmnyn** [comment]
Yep that solved the problem.  Sorry for missing that important piece of information!
