### ISSUE TITLE
Exporting error in rake export:all_volumes

### ISSUE THREAD

**Issue by villalbamartin** [acl-org/acl-anthology#89]
When running `rake export:all_volumes`, the task stops with the following error:

```
Exporting DBLP for volume Y99-1
Exporting volume A83-1
rake aborted!
NoMethodError: undefined method `attachment' for #<Paper:0x000000041570a8>
/home/aclanthology/.rvm/gems/ruby-2.0.0-p353@acl/gems/activemodel-4.0.1/lib/active_model/attribute_methods.rb:439:in `method_missing'
/home/aclanthology/.rvm/gems/ruby-2.0.0-p353@acl/gems/activerecord-4.0.1/lib/active_record/attribute_methods.rb:155:in `method_missing'
/home/aclanthology/acl-anthology/lib/tasks/xml_export.rake:83:in `block in export_papers_in_volume'
/home/aclanthology/acl-anthology/lib/tasks/xml_export.rake:21:in `each'
/home/aclanthology/acl-anthology/lib/tasks/xml_export.rake:21:in `export_papers_in_volume'
/home/aclanthology/acl-anthology/lib/tasks/xml_export.rake:148:in `block (5 levels) in <top (required)>'
/home/aclanthology/acl-anthology/lib/tasks/xml_export.rake:143:in `each'
/home/aclanthology/acl-anthology/lib/tasks/xml_export.rake:143:in `block (4 levels) in <top (required)>'
/home/aclanthology/acl-anthology/lib/tasks/xml_export.rake:133:in `each'
/home/aclanthology/acl-anthology/lib/tasks/xml_export.rake:133:in `block (3 levels) in <top (required)>'
/home/aclanthology/acl-anthology/lib/tasks/xml_export.rake:132:in `each'
/home/aclanthology/acl-anthology/lib/tasks/xml_export.rake:132:in `block (2 levels) in <top (required)>'
/home/aclanthology/acl-anthology/lib/tasks/all_export.rake:46:in `block (2 levels) in <top (required)>'
/home/aclanthology/.rvm/gems/ruby-2.0.0-p353@acl/bin/ruby_executable_hooks:15:in `eval'
/home/aclanthology/.rvm/gems/ruby-2.0.0-p353@acl/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => export:xml
(See full trace by running task with --trace)
```

Not sure whether it's related or not, but the line marked as causing the problem is `lib/tasks/xml_export.rake:83`, seen here:
https://github.com/acl-org/acl-anthology/blob/7b89d3c6d36c81c76a08107901cab788659e3442/lib/tasks/xml_export.rake#L83

and it is preceded by a funny comment:

```
# TODO: To be checked for correct export later!
if @paper.attachment != "none"
```

but since this was not an issue until now, it might not be related.

I'll keep looking into it, but I accept ideas and/or suggestions.

**Comment by knmnyn** [comment]
This seems to be a problem introduced by a dependency on the push that @animeshprasad made on being able to accept attachments.  Adding him into the dependency.
